spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: 3651551
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sms:
    eskiz:
      email: diyorbek2110@gmail.com
      password: bd4TYwGbetC10xklJN7J9OiYBPAXpRDD1uHiWtg2

