spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: diyor5712001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

